channel = discord.utils.get(client.get_all_channels(), id='some voice channel id', type=discord.enums.ChannelType.voice)
# channel = discord.utils.find(lambda m: m.id == 204127950931623937 and m.type == discord.enums.ChannelType.voice, client.get_all_channels())
print(channel)
voice = await client.join_voice_channel(channel)
player = voice.create_ffmpeg_player('assets/test.mp3')
player.start()
# print(message.author.voice.voice_channel.bitrate)
# voice = await client.join_voice_channel(message.author.voice.voice_channel)
# player = voice.create_ffmpeg_player('test.mp3')
# player.start()